---
name: test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.x'
      - name: cache Go
        if: ${{github.event_name == 'pull_request'}}
        uses: actions/cache@v2
        env:
          cache-name: go-cache
        with:
          path: "~/.cache/go-build"
          key: ${{ runner.os }}-${{ env.cache-name }}-1-${{github.event.pull_request.head.sha}}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-1-${{github.event.pull_request.base.sha}}
            ${{ runner.os }}-${{ env.cache-name }}-1-
      - name: cache Go
        if: ${{github.event_name == 'push'}}
        uses: actions/cache@v2
        env:
          cache-name: go-cache
        with:
          path: "~/.cache/go-build"
          key: ${{runner.os}}-${{env.cache-name}}-1-${{github.event.after}}
          restore-keys: |
            ${{runner.os}}-${{env.cache-name}}-1-${{github.event.before}}
            ${{runner.os}}-${{env.cache-name}}-1-
      - name: cache Go Module
        uses: actions/cache@v2
        env:
          cache-name: go-module
        with:
          path: "~/go/pkg/mod"
          key: ${{ runner.os }}-${{env.cache-name}}-1-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{runner.os}}-${{env.cache-name}}-1-
      - name: Test
        run: time go test -v -race ./...
