---
name: test
on:
  push:
    branches:
      - master
  pull_request: null
jobs:
  test:
    timeout-minutes: 30
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.x'
      - name: cache Go
        uses: actions/cache@v2
        env:
          cache-name: go-cache
        with:
          path: "~/.cache/go-build"
          key: ${{ runner.os }}-${{ env.cache-name }}-1-${{github.sha}}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-1-
      - name: cache Go Module
        uses: actions/cache@v2
        env:
          cache-name: go-module
        with:
          path: "~/go/pkg/mod"
          key: ${{ runner.os }}-${{env.cache-name}}-1-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{runner.os}}-${{env.cache-name}}-1-
      - name: Test
        run: time go test -v -race ./...
