---
name: test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.x'
      - name: cache Go
        if: ${{github.event_name == 'pull_request'}}
        uses: actions/cache@v2
        env:
          cache-name: go-cache
        with:
          path: ${{ env.GOCACHE }}
          key: ${{ runner.os }}-${{ env.cache-name }}-1-${{github.event.pull_request.base.sha}}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-1-
      - name: cache Go
        if: ${{github.event_name == 'push'}}
        uses: actions/cache@v2
        env:
          cache-name: go-cache
        with:
          path: ${{env.GOCACHE}}
          key: ${{runner.os}}-${{env.cache-name}}-1-${{env.GITHUB_SHA}}
          restore-keys: |
            ${{runner.os}}-${{env.cache-name}}-1-
      - name: Test
        run: time go test -v -race ./...
